# fly.toml file generated for fly-node on 2021-07-22T08:53:40+02:00

app = "fly-node"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builtin = "node"

[env]
  PRIMARY_REGION = "iad"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3500
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
